import blinxSensor


# TODO
    # blinxSensor.Blinx
        # blinxSensor.Blinx().save
        # blinxSensor.Blinx().get_index
        # blinxSensor.Blinx().get_time_buffer
        # blinxSensor.Blinx().buffer_to_log
    # blinxSensor.Sensor
        # blinxSensor.Sensor()._create_channels
        # blinxSensor.Sensor().read
        # blinxSensor.Sensor().write
        # blinxSensor.Sensor().save
        # blinxSensor.Sensor().get_index
        # blinxSensor.Sensor().get_time_buffer
        # blinxSensor.Sensor().buffer_to_log
    # blinxSensor.Channel
        # blinxSensor.Channel()._configure
        # blinxSensor.Channel().read
        # blinxSensor.Channel().write
        # blinxSensor.Channel().save
        # blinxSensor.Channel().buffer_save
        # blinxSensor.Channel().buffer_to_log
        # blinxSensor.Channel().save_value_in_log
        # blinxSensor.Channel().sum_bytes
        # blinxSensor.Channel().get_time_buffer
        # blinxSensor.Channel().get_index
    # blinxSensor.DigitalChannel
        # blinxSensor.DigitalChannel().read
        # blinxSensor.DigitalChannel().write
        # blinxSensor.AnalogChannel().read
        # blinxSensor.AnalogChannel().write
    # blinxSensor.I2CChannel
        # blinxSensor.I2CChannel().read
        # blinxSensor.I2CChannel().write
        # blinxSensor.I2CChannel().read_i2c
    # blinxSensor.Buffer
        # blinxSensor.Buffer().append
        # blinxSensor.Buffer().reset_index
        # blinxSensor.Buffer().get_index
        # blinxSensor.Buffer().last_time
        # blinxSensor.Buffer().missing
        # blinxSensor.Buffer().fix_missing_data
        # blinxSensor.Buffer().set_time
        # blinxSensor.Buffer().clear
    # blinxSensor.CircularBuffer
        # blinxSensor.CircularBuffer().get_partial
        # blinxSensor.CircularBuffer().get_all
        # blinxSensor.CircularBuffer().get_list_modify
        # blinxSensor.CircularBuffer().save
        # blinxSensor.CircularBuffer().array_to_str
        # blinxSensor.CircularBuffer().get_data
        # blinxSensor.CircularBuffer().reverse_bytearray

    # blinxSensor.next_time
    # blinxSensor.sensors_create_dict
    # blinxSensor.reset_ticks
    # blinxSensor.diff_ticks